# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: 
  vmImage: azrelease

stages:

- stage: Deploy
  displayName: 'Deploy Stage'
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          az login
      displayName: 'Login Azure'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          ids=$(az webapp list --query '[0].id' -o tsv)
          repo_url=https://github.com/bha1212002/food-app-project
          az webapp deployment source config --branch master --manual-integration --repo-url $repo_url --ids $ids
          az webapp deployment source sync --ids $ids
      displayName: 'Push Azure'